name: Ruff Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Oder eine andere Version, falls benötigt

      - name: Ruff installieren
        run: pip install ruff

      - name: Code mit Ruff prüfen
        run: ruff check .
